### ISSUE TITLE
Explain the "DNA" concept

### ISSUE THREAD

**Issue by tredondo** [jesse-ai/docs#56]
"DNA" is first used at https://docs.jesse.trade/docs/optimize/executing-the-optimize-mode#optimal-trades but it's not found in the previous Strategy Optimization pages. It's also not clearly explained in the Genetic Algorithms video. Maybe it's used in the Jesse UI, but a visitor who is perusing the docs before deciding to use Jesse won't have seen the UI.

The term "DNA" should be explained from the Jesse perspective before it is used.

**Comment by saleh-mir** [comment]
My assumption was that the user has read the introduction page first which has a video explaining genetic algorithms:

https://docs.jesse.trade/docs/optimize/

**Comment by tredondo** [comment]
Right, but the video doesn't clearly explain *the term "DNA"* either.

**Comment by saleh-mir** [comment]
I will add something.

**Comment by saleh-mir** [comment]
I think this page is clear enough:
https://docs.jesse.trade/docs/optimize/dna-usage
