### ISSUE TITLE
Explain more clearly what Jesse can do

### ISSUE THREAD

**Issue by tredondo** [jesse-ai/docs#60]
Neither the home page nor the docs explain much that Jesse only supports crypto swaps, and candle-based backtesting (as opposed to general securities like Backtrader, from which many people may want to migrate after its [abandonment](https://github.com/backtrader2/backtrader/issues/92)), or HFT via tick feeds.

https://docs.jesse.trade/docs/getting-started/ starts with how to install, then gets lost into details about Docker etc. A clearer introduction would mention what Jesse is, what it can do, and the key concepts.

**Comment by saleh-mir** [comment]
I just checked out the documentation and you're right, it doesn't mention it in the beginning, but my assumption is that the user has already seen either the website or the GitHub repository which do mention cryptocurrency word. Also, just so you know, I do intend to expand to support other markets such as Forex and stocks, but that's for far away in the future.
