### ISSUE TITLE
Roadmap is out of date

### ISSUE THREAD

**Issue by tredondo** [jesse-ai/docs#61]
https://docs.jesse.trade/docs/roadmap says "Starting in Q2 of 2021, **we will begin listing** our upcoming goals on this roadmap page."

Most of that page belongs into the Changelog actually because it's a list of features successfully implemented (congrats, BTW!). A roadmap should only have future/planned features (i.e. the "Beyond" section). Another option would be to move the Q2 2021 through Q4 2023 headings into a "History" section.

**Comment by saleh-mir** [comment]
What you're suggesting is a valid option, but I think the current way also works. I have seen it in other projects. Thank you for your suggestion.
