### ISSUE TITLE
self.is_open is undefined

### ISSUE THREAD

**Issue by Gabri** [jesse-ai/docs#7]
reading https://docs.jesse-ai.com/docs/strategies/api.html#position it seems possibile to use self.is_open as an alias of self.position.is_open but it seems it doesn't work:
Uncaught Exception: AttributeError: 'BottinoTest' object has no attribute 'is_open'.
Maybe the same for self.is_close (haven't tried)

**Comment by saleh-old** [comment]
Sorry for some reason Github emails were going into my spam folder. I just saw this. I'll look into it soon

**Comment by saleh-old** [comment]
Looks like I wanted the API to have them but didn't actually implement the code. 

I added them to the source code now, and updated docs too. Upgrade to `v0.1.0`
